import type { PriceCategory } from "../schemas/tour.schema"

export const DEFAULT_PRICE_CATEGORIES: readonly PriceCategory[] = [
	{
		name: "Adulto",
		price: 0,
		receptionPrice: 0,
		transferPrice: 0,
		minPrice: 0,
		maxPrice: 0,
		ageMin: 12,
		ageMax: 64,
		isDefault: true,
		isSpecial: false,
		sortOrder: 0,
		active: true,
		entries: [],
	},
	{
		name: "Niño",
		price: 0,
		receptionPrice: 0,
		transferPrice: 0,
		minPrice: 0,
		maxPrice: 0,
		ageMin: 0,
		ageMax: 11,
		isDefault: true,
		isSpecial: false,
		sortOrder: 1,
		active: true,
		entries: [],
	},
	{
		name: "Adulto Mayor",
		price: 0,
		receptionPrice: 0,
		transferPrice: 0,
		minPrice: 0,
		maxPrice: 0,
		ageMin: 65,
		ageMax: null,
		isDefault: true,
		isSpecial: false,
		sortOrder: 2,
		active: true,
		entries: [],
	},
]
